export const weddingData = {
  code: 'ROHITMAN',
  heroData: {
    groomName: "Rohit",
    brideName: "Manpreet",
    groomParents: "S/O Harsha Methwani & Ramesh Methwani",
    brideParents: "D/O Rupinder Kaur Sohal & Charanjith Singh Sohal",
    weddingDate: "22 & 23",
    weddingMonth: "NOV",
    weddingYear: "2026",
    weddingTime: "", // User said keep only dates without time
  },
  ourStory: {
    sectionLabel: "Our Story",
    headingLine1: "How We",
    headingLine2: "Met",
    storyText: "What started as an ordinary evening turned into a lifetime of shared laughs, endless dinner dates, and an undeniable love for fries. Somewhere between late-night texts and conversations, we realized that home was never a place—it was each other.",
  },
  events: [
    {
      id: "thread-ceremony",
      sectionLabel: "Thread Ceremony",
      eventName: "Thread Ceremony",
      name: "Thread Ceremony",
      iconSrc: "/assets/templates/royal-heirloom/caricature/thread ceremony.png",
      date: "22nd Nov 2026",
      time: "11:00 AM onwards",
      venueName: "Pool Side",
      dressCode: "Light Traditional",
      caricatureColor: "",
      mapUrl: "",
    },
    {
      id: "rings-rhythm",
      sectionLabel: "Rings & Rhythm",
      eventName: "Rings & Rhythm",
      name: "Rings & Rhythm",
      iconSrc: "/assets/templates/royal-heirloom/caricature/ring-rhythm.png",
      date: "22nd Nov 2026",
      time: "7:00 PM onwards",
      venueName: "Ballroom 1 & 2",
      dressCode: "Indo-Western Glam",
      caricatureColor: "",
      mapUrl: "",
    },
    {
      id: "anand-karaj",
      sectionLabel: "Anand Karaj",
      eventName: "Anand Karaj",
      name: "Anand Karaj",
      iconSrc: "/assets/templates/royal-heirloom/caricature/redandcream.png",
      date: "23rd Nov 2026",
      time: "9:00 AM onwards",
      venueName: "Shri Nabha Sahib Gurudwara",
      dressCode: "Elegant Indian Wear",
      caricatureColor: "",
      mapUrl: "",
    },
    {
      id: "baraat-lunch",
      sectionLabel: "Baraat & Lunch",
      eventName: "Baraat & Lunch",
      name: "Baraat & Lunch",
      iconSrc: "/assets/templates/royal-heirloom/caricature/redandcream.png",
      date: "23rd Nov 2026",
      time: "1:00 PM onwards",
      venueName: "Grand Ballroom",
      dressCode: "Elegant Indian Wear",
      caricatureColor: "",
      mapUrl: "",
    },
    {
      id: "gala-evening",
      sectionLabel: "Gala Evening",
      eventName: "Gala Evening",
      name: "Gala Evening",
      iconSrc: "/assets/templates/royal-heirloom/caricature/gala evening.png",
      date: "23rd Nov 2026",
      time: "8:00 PM onwards",
      venueName: "Ballroom 1 & 2",
      dressCode: "Suits & Sparkle",
      caricatureColor: "",
      mapUrl: "",
    }
  ],
  venue: {
    venueName: "Park Plaza Hotel",
    venueLine1: "",
    venueLine2: "Chandigarh, Punjab, India",
    mapUrl: "https://maps.app.goo.gl/BDVynkUmTGZcEtQQ8?g_st=aw",
  },
  countdown: {
    headerTop: "COUNTING DOWN TO",
    targetDateTimeISO: "2026-11-23T09:00:00.000Z",
    labels: { days: "Days", hours: "Hours", minutes: "Min", seconds: "Sec" },
  },
  celebrate: {
    sectionLabel: "Celebrate & Bless Us",
    heading: "RSVP & Gift Registry",
    subtitle: "Your presence and blessings are our greatest gift. Kindly confirm your attendance or visit our registry below.",
    rsvp: {
      enabled: false,
    },
    registry: {
      enabled: false,
    }
  },
  loveAndRegards: {
    headline: "Love",
    familyNames: "Methwanis and Sohals",
  },
  footer: {
    headline: "With Love & Gratitude",
    names: "Rohit & Manpreet",
    watermark: "INVITEQUE",
  }
};
