import { API_URL } from '../config';

/**
 * Uploads a file directly to Cloudflare R2 using a pre-signed URL generated by the backend.
 * 
 * @param {File} file - The compressed File object to upload.
 * @returns {Promise<string>} - The public URL of the uploaded image.
 */
export async function uploadToR2(file) {
  try {
    // 1. Get pre-signed URL from our backend
    // Clean filename to prevent issues
    const cleanFileName = file.name.replace(/[^a-zA-Z0-9.-]/g, '_');
    
    // Get token from AuthContext's storage key
    const storedUser = localStorage.getItem('inviteque_user');
    const token = storedUser ? JSON.parse(storedUser).token : null;
    
    // We append a timestamp to ensure uniqueness
    const uniqueFilename = `${Date.now()}-${cleanFileName}`;
    
    const response = await fetch(`${API_URL}/api/v1/media/upload-url?filename=${encodeURIComponent(uniqueFilename)}`, {
      method: 'GET',
      headers: {
        'Authorization': `Bearer ${token}`
      }
    });

    if (!response.ok) {
      throw new Error(`Failed to get upload URL: ${response.statusText}`);
    }

    const { preSignedUrl, publicUrl } = await response.json();

    // 2. Upload the file directly to R2
    const uploadResponse = await fetch(preSignedUrl, {
      method: 'PUT',
      body: file,
      headers: {
        'Content-Type': file.type
      }
    });

    if (!uploadResponse.ok) {
      throw new Error(`Failed to upload to R2: ${uploadResponse.statusText}`);
    }

    // 3. Return the public URL for storage in the DB
    return publicUrl;
  } catch (error) {
    console.error("Error in uploadToR2:", error);
    throw error;
  }
}
